# Generated by Django 5.2 on 2026-02-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='User_list',
        ),
    ]
