# Generated by Django 5.2 on 2026-02-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_articles_htmls_images_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='limit_reader',
            field=models.BooleanField(default=False),
        ),
    ]
