# Generated by Django 5.2 on 2026-02-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_articles_public_alter_articles_limit_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_reader',
            field=models.BooleanField(default=False),
        ),
    ]
