# Generated by Django 5.2 on 2026-02-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_users_is_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='summary',
            field=models.CharField(default='Summary is nothing', max_length=100),
            preserve_default=False,
        ),
    ]
