# Generated by Django 5.2 on 2026-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_articles_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
