# Generated by Django 5.2 on 2026-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_articles_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='reader_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
