# Generated by Django 5.2 on 2026-02-26 05:42

import blog_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_articles_reader_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.FileField(upload_to=blog_app.models.article_directory_path)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='blog_app.articles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
