# Generated by Django 5.2 on 2026-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_audios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='reader_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
