# Generated by Django 5.2 on 2026-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_articles_reader_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmls',
            name='html',
            field=models.TextField(),
        ),
    ]
